### ISSUE TITLE
switch package download stats url

### ISSUE THREAD

**Issue by tfoote** [DLu/ros_metrics#2]
Looking at your script it appears to be using the urldetails page from awstats not the downloads page. And it appears to not list most of the debian package downloads on that page.

https://github.com/DLu/ros_metrics/blob/8c8825e6a17fe55685852006c0bd06c90bff3ee0/ros_metrics/packages.py#L16

https://awstats.osuosl.org/reports/packages.ros.org/2019/10/awstats.packages.ros.org.downloads.html
vs 
https://awstats.osuosl.org/reports/packages.ros.org/2019/10/awstats.packages.ros.org.urldetail.html

The downloads page has more content. I believe that the direct fetches of the binaries are not included in the URL listings. Switching should give much more accurate results.

I'll see if we can get that to not be truncated and then hopefully it won't be necessary to setup mechanisms to pull the logs internally.

**Comment by DLu** [comment]
Ah, so the downloads page doesn't exist for all months, but it is there for
the more recent months where the numbers are the most off.

For July of this year, we go from 100% kinetic (which is what the urldetail
page says) to 66% kinetic, 30% melodic and 4% indigo. That's somewhat close
to your metrics report, except its missing the lunar and ROS2 repos, each
of which has a smaller percentage than indigo.

In order to get it to match, I think we would need the untruncated version.

**Comment by tfoote** [comment]
I've filed a ticket with OSUOSL to ask them to change the max number of lines in a response to 100k from the current 1k which gets us all but the very longest of the tail so we can automate this.

**Comment by DLu** [comment]
Can I get a link to that ticket? Or at least a post here when it is closed? That way I can force a recrawl.

**Comment by tfoote** [comment]
Yeah, I'll let you know when it's resolved.
